### ISSUE TITLE
Searching not working

### ISSUE THREAD

**Issue by tsjazil** [PandaFoss/baph#2]
![1644048423](https://user-images.githubusercontent.com/45793120/152634024-8ade64b9-97fd-4cce-8eab-de2849c2ebea.jpg)

**Comment by tsjazil** [comment]
Tried reinstalling baph but not working

**Comment by cr1spyapple** [comment]
Try install baph from [here](https://bitbucket.org/natemaia/baph/src/master/), that is what i use. It was linked on the README of this fork.

**Comment by tsjazil** [comment]
Thanks its working 👍🏽

**Comment by cr1spyapple** [comment]
No problem :)
